### MOVIES
GET http://localhost:3000/movies

### MOVIE BY ID
GET http://localhost:3000/movies/bb79862c-be5a-11ee-af20-3e79a5ce1913

### MOVIES BY QUERY
GET http://localhost:3000/movies?genre=Crime

### CREATE MOVIE
POST http://localhost:3000/movies
Content-Type: application/json
x-user-key-name: notSanti

{
    "title": "Endgame",
    "year": 2017,
    "director": "Joss Whedon",
    "duration": 150,
    "poster": "https://img.fruugo.com/product/7/41/14532417_max.jpg",
    "genre": [
      "Action",
      "Adventure",
      "Sci-Fi"
    ],
    "rate": 10
  }

### MODIFY AN EXISTING MOVIE
PATCH http://localhost:3000/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3
Content-Type: application/json

{
    "year": 2000
}

### MOVIE DELETE
DELETE http://localhost:3000/movies/b9b9cfd2-3e64-44d5-9fa7-4c7e2a45d21b